export const ADD_NEWONE_TASK = "ADD_NEWONE_TASK";
export const TOGGLE_ITEM_TASK = "TOGGLE_ITEM_TASK";
export const EDIT_ITEM_TASK = "EDIT_ITEM_TASK";
export const DELET_ITEM_TASK = "DELET_ITEM_TASK";
export const SELECT_ALL_ITEMS_TASK = "SELECT_ALL_ITEMS_TASK";
export const DELETE_SELECTED_ITEMS_TASK = "DELETE_SELECTED_ITEMS_TASK";
export const SET_STORE = "SET_STORE";
